# Generated by Django 4.1.2 on 2022-12-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupac_ime', models.CharField(max_length=100)),
                ('kupac_prezime', models.CharField(max_length=100)),
                ('kupac_email', models.EmailField(max_length=254)),
                ('kupac_adresa', models.CharField(max_length=150)),
                ('kupac_placanje', models.CharField(max_length=50)),
            ],
        ),
    ]
