# Generated by Django 4.1.2 on 2022-12-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoodie_brand', models.CharField(max_length=100)),
                ('hoodie_size', models.CharField(max_length=4)),
                ('hoodie_color', models.CharField(max_length=15)),
                ('hoodie_naziv', models.CharField(max_length=70)),
                ('hoodie_price', models.FloatField()),
                ('hoodie_discount', models.FloatField()),
                ('hoodie_slika', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pants_brand', models.CharField(max_length=100)),
                ('pants_waist', models.FloatField(max_length=5)),
                ('pants_length', models.FloatField()),
                ('pants_color', models.CharField(max_length=15)),
                ('pants_naziv', models.CharField(max_length=70)),
                ('pants_price', models.FloatField()),
                ('pants_discount', models.FloatField()),
                ('pants_slika', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt_brand', models.CharField(max_length=100)),
                ('tshirt_waist', models.FloatField(max_length=5)),
                ('tshirt_length', models.FloatField()),
                ('tshirt_color', models.CharField(max_length=15)),
                ('tshirt_naziv', models.CharField(max_length=70)),
                ('tshirt_price', models.FloatField()),
                ('tshirt_discount', models.FloatField()),
                ('tshirt_slika', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VrstaProizvoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrstaP_naziv', models.CharField(max_length=50)),
            ],
        ),
    ]
