# Generated by Django 4.1.2 on 2022-12-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hoodie_pants_tshirt_vrstaproizvoda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_country', models.CharField(max_length=30)),
                ('adress_city', models.CharField(max_length=80)),
                ('adress_name', models.CharField(max_length=100)),
                ('adress_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proizvod_brand', models.CharField(max_length=100)),
                ('proizvod_size', models.CharField(max_length=4)),
                ('proizvod_color', models.CharField(max_length=15)),
                ('proizvod_naziv', models.CharField(max_length=70)),
                ('proizvod_price', models.FloatField()),
                ('proizvod_discount', models.FloatField()),
                ('proizvod_slika', models.URLField()),
                ('proizvod_vrstaP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vrstaproizvoda')),
            ],
        ),
        migrations.DeleteModel(
            name='Hoodie',
        ),
        migrations.DeleteModel(
            name='Pants',
        ),
        migrations.DeleteModel(
            name='Tshirt',
        ),
        migrations.AddField(
            model_name='kupac',
            name='kupac_proizvodi',
            field=models.ManyToManyField(to='main.proizvod'),
        ),
        migrations.AlterField(
            model_name='kupac',
            name='kupac_adresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.adress'),
        ),
    ]
