# Generated by Django 4.1.2 on 2022-12-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adress_proizvod_delete_hoodie_delete_pants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kupac',
            name='kupac_adresa',
        ),
        migrations.RemoveField(
            model_name='kupac',
            name='kupac_proizvodi',
        ),
    ]
