# Generated by Django 4.1.2 on 2022-12-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_kupac_kupac_adresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvod',
            name='proizvod_vrstaP',
        ),
    ]
