# Generated by Django 4.1.2 on 2022-12-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_proizvod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kupac',
            name='kupac_proizvodi',
        ),
        migrations.AddField(
            model_name='kupac',
            name='kupac_adresa',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.adress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proizvod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
