# Generated by Django 4.1.2 on 2022-12-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_kupac_kupac_proizvodi_kupac_kupac_adresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kupac',
            old_name='kupac_adresa',
            new_name='kupac_adresa_id',
        ),
    ]
