# Generated by Django 4.1.2 on 2022-12-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_kupac_adresa_kupac_kupac_adresa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kupac',
            old_name='kupac_adresa_id',
            new_name='kupac_adresa',
        ),
        migrations.AlterField(
            model_name='adress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
