# Generated by Django 3.2.16 on 2022-12-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_adress_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kupac',
            name='kupac_proizvodi',
            field=models.ManyToManyField(to='main.Proizvod'),
        ),
    ]
